/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/common/BaseCard.vue')['default']
    BaseInput: typeof import('./src/components/common/BaseInput.vue')['default']
    ExampleButton: typeof import('./src/components/common/ExampleButton.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
